AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Service1Name:
    Type: String
    Description: ECR Repository Name


Resources:

  Repository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref Service1Name

Outputs:
  Service1Repository:
    Value: !Ref 'Repository'
    Export:
      Name: !Sub '${AWS::StackName}-Service1Repository'
  Service1RepositoryUrl:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}"
    Export:
      Name: !Sub '${AWS::StackName}-Service1RepositoryUrl'
